finished setup-reaper

diff --git a/commands/install-reaper b/commands/install-reaper
--- a/commands/install-reaper
+++ b/commands/install-reaper
@@ -1,45 +1,53 @@
 #!/usr/bin/env bash
 
-# TODO: validate $1 path
-install_path="$REAPER_DIR/app/${1-$RPP_LATEST_DIR}"
+install_path="$REAPER_APP_DIR/${1-reaper}"
+user=$(git config github.user)
 
-# if $1 not set
 if test -z "${1-}"; then
-    app_name="rpp-latest.app"
+    # default
+    app_name="reaper.app"
 else
     app_name="$1.app"
 fi
 
-original="REAPER64.app"
+original="REAPER.app"
+
+# echo "ip: $install_path"
+# echo "an: $app_name"
 
 # or if  $1 == $RPP_LATEST_DIR exit
 if ! test -d $install_path; then
 
     echo-green "Installing latest version of Reaper to $install_path"
 
-    git clone https://github.com/molleweide/reaper-config.git $install_path
+	echo "Setting up reaper config."
+	if test -n "$user"; then
+		reaperConfig="git@github.com:$user/reaper-config.git"
+		if ! confirm-bool "Does this repository house your Reaper configuration? [$reaperConfig]"; then
+			reaperConfig=''
+		fi
+	fi
+
+	echo "Cloning the Reaper configuration into $install_path"
+	if ! git clone "$reaperConfig" $install_path; then
+		echo "The clone of the repository [$reaperConfig] to [$install_path] failed."
+		echo "Dorothy will initialise the directory as a git repository, and leave it up to you to sync it up with a remote."
+		echo
+		pushd $install_path > /dev/null || exit 1
+		silent git init
+		popd > /dev/null || exit 1
+	else
+        pushd $install_path > /dev/null 2>&1
+        # echo "pwd: $PWD"
+        git checkout $GIT_DEFAULT_BRANCH
+        # git reset --hard HEAD
+        git submodule update --init --recursive
+        # cd Scripts/reaper-keys && git checkout molleweide && cd ../..
+        # cd Effects/molleweide && git checkout molleweide && cd ../..
+        # cd ColorThemes && git checkout molleweide && cd ..
+        popd > /dev/null 2>&1
+	fi
 
     brew install --cask reaper --appdir=$install_path --force
-
-
     $(mv $install_path/$original $install_path/$app_name)
-
-    # tmp_dir=$(mkdtemp $REAPER_DIR)
-
-    # CLONE GIT TO TMP DIR AND MOVE IT TO REAPER
-    # mv $tmp_dir/.git $install_path/.git
-    # rm -r $tmp_dir # be careful
-
-    # INSTALL REAPER TO TARGET DIR AND RENAME TO LATEST VERSION
-    # mkdir -p $install_path
-
-    # NAVIGATE TO (pushd/popd) REAPER INSTALL DIR AND RESTORE GIT
-    pushd $install_path > /dev/null 2>&1
-    git checkout rpp-latest
-    git reset --hard HEAD
-    git submodule update --init --recursive
-    cd Scripts/reaper-keys && git checkout molleweide && cd ../..
-    cd Effects/molleweide && git checkout molleweide && cd ../..
-    cd ColorThemes && git checkout molleweide && cd ..
-    popd > /dev/null 2>&1
 fi
