save

diff --git a/commands/setup-util-reaper b/commands/setup-util-reaper
--- a/commands/setup-util-reaper
+++ b/commands/setup-util-reaper
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-echo-header "SETUP REAPER"
+echo-style --g1="SETUP REAPER"
 
 # https://forum.cockos.com/showthread.php?p=2487247#post2487247
 # https://forum.cockos.com/showthread.php?t=242922&highlight=reaper+update+utility
@@ -19,38 +19,41 @@ mkdir -p $REAPER_DIR/projects
 mkdir -p $REAPER_DIR/tmp
 mkdir -p $REAPER_DIR/backup
 
+export GIT_DEFAULT_BRANCH="molleweide" # rm...
+
 github_user=$(git config github.user)
 install_path="$REAPER_APP_DIR/${1-reaper}"
 app_name="${1-reaper}.app"
 
 if ! test -d $install_path; then
-    if confirm-bool "Do you want to install Reaper to [$install_path]?"; then
-        install-reaper
-    else
+    if ! confirm-bool --ppid=$$ -- "Do you want to install Reaper to [$install_path]?"; then
+    #     install-reaper
+    # else
         exit 1
     fi
 else
-    echo-bold "Reaper already exists at '$install_path'. \ You can install a new instance by 'setup-reaper <name>'."
+    echo-style --g3="Reaper already exists at '$install_path'. \ You can install a new instance by 'setup-reaper <name>'."
     exit 1
 fi
 
 if ! test -d $install_path; then
-    echo-green "Installing latest version of Reaper to $install_path"
+    echo-style --green="Installing latest version of Reaper to $install_path"
 	if test -n "$github_user"; then
 		reaperConfig="git@github.com:$github_user/reaper-config.git"
-		if ! confirm-bool "Does this repository house your Reaper configuration? [$reaperConfig]"; then
+		if ! confirm-bool --ppid=$$ -- "Does this repository house your Reaper configuration? [$reaperConfig]"; then
 			reaperConfig=''
 		fi
 	fi
-	echo "Cloning the Reaper configuration into $install_path"
+	echo-style --purple="Cloning the Reaper configuration into $install_path"
 	if ! git clone "$reaperConfig" $install_path; then
-		echo "The clone of the repository [$reaperConfig] to [$install_path] failed."
-		echo "Dorothy will initialise the directory as a git repository, and leave it up to you to sync it up with a remote."
-		echo
+		echo-style --orange="The clone of the repository [$reaperConfig] to [$install_path] failed."
+		echo-style --orange="Dorothy will initialise the directory as a git repository, and leave it up to you to sync it up with a remote."
+		echo-style
 		pushd $install_path > /dev/null || exit 1
 		silent git init
 		popd > /dev/null || exit 1
 	else
+	    echo-style --magenta="checkout branch ($GIT_DEFAULT_BRANCH)!!"
         pushd $install_path > /dev/null 2>&1
         git checkout $GIT_DEFAULT_BRANCH
         git submodule update --init --recursive
@@ -59,7 +62,7 @@ if ! test -d $install_path; then
         # cd ColorThemes && git checkout molleweide && cd ..
         popd > /dev/null 2>&1
 	fi
-	echo "Downloading the reaper executable."
+	echo-style --g2="Downloading the reaper executable."
     brew install --cask reaper --appdir=$install_path --force
     $(mv "$install_path/REAPER.app" $install_path/$app_name)
 fi
