save

diff --git a/commands/setup-util-stack b/commands/setup-util-stack
--- a/commands/setup-util-stack
+++ b/commands/setup-util-stack
@@ -3,12 +3,18 @@
 # https://github.com/golang/go/wiki/Ubuntu
 
 function setup_util_stack() (
-	if command-exists curl; then
-		curl -sSL https://get.haskellstack.org/ | sh
-	elif command-exists wget; then
-		wget -qO- https://get.haskellstack.org/ | sh
+
+	if ! command-exists stack; then
+
+		if command-exists curl; then
+			curl -sSL https://get.haskellstack.org/ | sh
+		elif command-exists wget; then
+			wget -qO- https://get.haskellstack.org/ | sh
+		else
+			echo-error "Failed to install Stack. Neither [curl] or [wget] command exists on system."
+		fi
 	else
-		echo-error "Failed to install Stack. Neither [curl] or [wget] command exists on system."
+		echo "STACK EXISTS"
 	fi
 )
 
